[package]
name = "nbis-rs"
version = "0.1.17"
edition = "2024"
rust-version = "1.95.0"

authors = ["Varun Chatterji <varun@seventhsense.ai>"]
description = "A Rust binding to the NIST Biometric Image Software (NBIS) library, which is used for processing biometric images, particularly in the context of fingerprint recognition"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Seventh-Sense-Artificial-Intelligence/nbis-rs"
homepage = "https://github.com/Seventh-Sense-Artificial-Intelligence/nbis-rs"
documentation = "https://docs.rs/nbis-rs"
keywords = ["biometrics", "fingerprint", "nbis"]
categories = ["algorithms", "api-bindings"]
publish = true

exclude = ["/.github", "/examples", "/test_data", "/scripts", "/.vscode", "/.venv"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi_bindgen.rs"

[lib]
crate-type = ["lib", "cdylib"]
name = "nbis"

[dependencies]
image = "0.25"
imageproc = "0.25"
thiserror = "2.0"
uniffi = { version = "0.29", features = ["cli"] }

[build-dependencies]
cc = "1.2"
cmake = "0.1"
pkg-config = "0.3"
uniffi = { version = "0.29", features = ["build"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 1

[profile.bench]
opt-level = 3
lto = true
codegen-units = 1
